version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  e2e-module:
    image: mytheresa/demo
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - URL=https://www.mytheresa.com/int_en/men.html?rd=1int
      - MODULE=E2ETests.xml